project:
  type: website
  output-dir: docs

website:
  title: "Herramientas para el manejo de datos de biodiversidad en R"
  sidebar:
    background: primary
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/luisDVA/curso-R-biodiversidad
        text: GitHub
    style: docked
    contents:
      - href: index.qmd
        text: Inicio
      - href: temario.qmd
        text: Temario y cronograma
      - href: materiales.qmd
        text: Materiales
  page-footer:
    left: "Página creada con [Quarto](https://quarto.org/)."
    right: "Luis D. Verde Arregoitia - 2023"



format:
  html:
    theme: lux
    toc: true

execute:
  freeze: auto

