project:
  type: website
  output-dir: docs

website:
  title: "Herramientas para el manejo de datos de biodiversidad en R"
  sidebar:
    background: primary
    # logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/Pakillo/quarto-course-website-template
        text: GitHub
    style: docked
    contents:
      - href: index.qmd
        text: Home
      - href: temario.qmd
        text: Temario y cronograma
      - href: materials.qmd
        text: Materials

format:
  html:
    theme: cosmo
    # css: styles.css
    toc: true

execute:
  freeze: auto

